name: time_luxe
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.1.2
  bloc: ^8.1.2
  cloud_firestore: ^4.8.3
  conditional_builder_null_safety: ^0.0.6
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  get: ^4.6.5
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  image_picker: ^1.0.4
  reusable_components:
    git:
      url: https://github.com/ahmedghaly15/Reusable-Components-Package
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/trending_products/
    - assets/images/image_change/
    - assets/images/bag/
    - assets/logos/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/global/
  filename: app_assets.dart
  field_prefix: null
